name: Other

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "**"]

jobs:
  check:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: apache/skywalking-eyes@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
        with:
          log: info
          config: .github/configs/skywalking-eyes.yml
