name: Other

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "**"]

jobs:
  check:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: apache/skywalking-eyes@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
        with:
          log: info
          config: .github/configs/skywalking-eyes.yml
