name: Other

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "**"]

jobs:
  check:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: apache/skywalking-eyes@v0.6.0
        with:
          log: info
          config: .github/configs/skywalking-eyes.yml
